# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geoip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgeoip.proto\x12\x12geoip.plugin.v2ray\"\"\n\x04\x43IDR\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0e\n\x06prefix\x18\x02 \x01(\r\"E\n\x05GeoIP\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12&\n\x04\x63idr\x18\x02 \x03(\x0b\x32\x18.geoip.plugin.v2ray.CIDR\"5\n\tGeoIPList\x12(\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x19.geoip.plugin.v2ray.GeoIPB%Z#github.com/v2fly/geoip/plugin/v2rayb\x06proto3')



_CIDR = DESCRIPTOR.message_types_by_name['CIDR']
_GEOIP = DESCRIPTOR.message_types_by_name['GeoIP']
_GEOIPLIST = DESCRIPTOR.message_types_by_name['GeoIPList']
CIDR = _reflection.GeneratedProtocolMessageType('CIDR', (_message.Message,), {
  'DESCRIPTOR' : _CIDR,
  '__module__' : 'geoip_pb2'
  # @@protoc_insertion_point(class_scope:geoip.plugin.v2ray.CIDR)
  })
_sym_db.RegisterMessage(CIDR)

GeoIP = _reflection.GeneratedProtocolMessageType('GeoIP', (_message.Message,), {
  'DESCRIPTOR' : _GEOIP,
  '__module__' : 'geoip_pb2'
  # @@protoc_insertion_point(class_scope:geoip.plugin.v2ray.GeoIP)
  })
_sym_db.RegisterMessage(GeoIP)

GeoIPList = _reflection.GeneratedProtocolMessageType('GeoIPList', (_message.Message,), {
  'DESCRIPTOR' : _GEOIPLIST,
  '__module__' : 'geoip_pb2'
  # @@protoc_insertion_point(class_scope:geoip.plugin.v2ray.GeoIPList)
  })
_sym_db.RegisterMessage(GeoIPList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/v2fly/geoip/plugin/v2ray'
  _CIDR._serialized_start=35
  _CIDR._serialized_end=69
  _GEOIP._serialized_start=71
  _GEOIP._serialized_end=140
  _GEOIPLIST._serialized_start=142
  _GEOIPLIST._serialized_end=195
# @@protoc_insertion_point(module_scope)
